project:
  pre-render:
    - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
    - _extensions/Afonenko-Course-Tools/project-download/entrypoints/pre.ts
    - _extensions/Afonenko-Course-Tools/course-core/entrypoints/owner-freeze.ts
  post-render:
    - _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
    - _extensions/Afonenko-Course-Tools/project-download/entrypoints/post.ts
  type: book
  output-dir: _book/student
  resources:
    - "!**/projects/**"
    - "!**/_control.qmd"
    - "!_generated/**"
profile:
  default: student
  group: [[student, full]]
course:
  id: course-essays
  validate: true
  view: student
course-pedagogy:
  document-defaults: true
work-mode: individual
filters: [course-core, course-presentation, project-download]
course-presentation:
  mode: study
book:
  title: Исследования программных контрактов
  sidebar:
    tools:
      - icon: house
        href: ../index.html#sec-course
        text: Навигация курса
  chapters:
    - index.qmd
    - part: text/index.qmd
      chapters:
        - text/representation/index.qmd
        - text/decoding/index.qmd
        - text/immutability/index.qmd
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    number-depth: 1
    code-copy: true
lang: ru

project-download:
  resources:
    exr-utf8-experiment:
      path: text/decoding/projects/experiment/student
      profiles: [full]
    exr-utf8-implementation:
      path: text/decoding/projects/implementation/student
      profiles: [full]
    exr-utf8-test-design:
      path: text/decoding/projects/test-design/student
      profiles: [full]
