project:
  type: default
  output-dir: _output
  render: [contracts.qmd]
lang: ru
format:
  pdf:
    output-file: contracts.pdf
    pdf-engine: xelatex
    papersize: a4
    fontsize: 11pt
    mainfont: DejaVu Serif
    sansfont: DejaVu Sans
    monofont: DejaVu Sans Mono
    colorlinks: true
    code-block-bg: true
crossref:
  exr-title: Задание
  exr-prefix: задание
  chapters: false
